version: '3.1'

services: 

     
     influencer:
      depends_on:
       - postgresdb
          
      build:
        context: ./
        dockerfile: Dockerfile
      restart: always
      
      environment:
           DATABASE_URL: postgresql://postgres:jk2003@postgresdb:5432/level_up_db?schema=public&connect_timeout=30&pool_timeout=30&socket_timeout=30
           INSTAGRAM_CLIENT_ID: your_client_id
           INSTAGRAM_CLIENT_SECRET: your_client_secret
           NEXT_AUTH_SECRET: your_next_auth_secret
           NEXTAUTH_URL: https://localhost:3000
      ports:
        - 3000:3000
        - 5555:5555
      
     postgresdb:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_PASSWORD: 'jk2003'
        POSTGRES_DB: level_up_db
      volumes: 
        - mydb:/level_up_db
      ports:
        - 5432:5432
  
volumes:
   mydb:
     
