version: '3.1'

services: 

     
     influencer:
      depends_on:
        postgresdb:
          condition: service_healthy
          restart: true
          
      build:
        context: ./
        dockerfile: Dockerfile
      restart: unless-stopped
      
      environment:
           DATABASE_URL: postgresql://postgres:jk2003@postgresdb:5432/level_up_db?schema=public
           INSTAGRAM_CLIENT_ID: 902780958221471
           INSTAGRAM_CLIENT_SECRET: 1cd38dda1047f2e1c91e1525ae719b02
           NEXT_AUTH_SECRET: JAI12062003MOHITE
           NEXTAUTH_URL: https://localhost:3000
      ports:
        - 3000:3000
        - 5555:5555
      command: ["/bin/sh", "-c", "npx prisma migrate dev --name init && npx prisma generate && npm run dev"]
      
     postgresdb:
      image: postgres:latest
      restart: unless-stopped
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 'jk2003'
        POSTGRES_DB: level_up_db
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
        interval: 10s
        timeout: 5s
        retries: 5
      volumes: 
        - mydb:/var/lib/postgresql/data
      ports:
        - 5432:5432
  
volumes:
   mydb:
     
