name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
      run:   
        echo "$SSH_PRIVATE_KEY" > newkey
        chmod 600 newkey 
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        ssh -t -i newkey ubuntu@ec2-13-232-241-230.ap-south-1.compute.amazonaws.com "sudo bash ~/deploy.sh"
