name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
      run: 

        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile 
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        echo "copied known_hosts"
        ssh -t -i keyfile ubuntu@ec2-65-2-150-89.ap-south-1.compute.amazonaws.com "sudo bash deploy.sh"


